version: "3.7"

services:
  django:
    build:
      context: ./app
    env_file:
      - ./.env
    # environment:
    #   - DJANGO_READ_ENV_FILE=False
    command: gunicorn djangosample1.wsgi --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - ./app:/usr/src/app

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - django

  # db-mysql:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
  #     MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  #     MYSQL_DATABASE: "${MYSQL_DATABASE}"
  #     MYSQL_USER: "${MYSQL_USER}"
  #     MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  #   ports:
  #   - 3306:3306
  #   volumes:
  #     - wp-mysql-volume:/var/lib/mysql
  #   restart: always

volumes:
  wp-mysql-volume: