# Generated by Django 3.0.7 on 2020-06-17 23:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jinjer', '0002_acountlist_execlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, verbose_name='ユーザID')),
                ('event_id', models.IntegerField()),
                ('detail', models.CharField(max_length=200, verbose_name='詳細')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
    ]
