# Generated by Django 3.0.7 on 2020-06-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jinjer', '0003_errorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='detail',
            new_name='message',
        ),
    ]
